## cost function weights

# terminal cost
weight_x_T: 0
weight_v_T: 1.0e-2

# initial cost
weight_x_i: 0
weight_v_i: 1.0e-2
weight_u_i: 1.0e-3
weight_s_i: 1.0e+4

# running cost
weight_x_t: 1.0e+4 # state
weight_s_t: 1.0e+4 # slack
weight_u_t: 1.0e-3 # control
weight_v_t: 1.0e-2 # velocity
weight_w_t: 1.0e-1 # jerk?



